#############################################################################
# Makefile for building: QxWrite
# Generated by qmake (3.1) (Qt 5.15.13)
# Project:  qxwrite.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile qxwrite.pro -spec linux-g++ CONFIG+=debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = QxWrite1.0.0
DISTDIR = /home/ares/Downloads/editor/QxWriteProject/.tmp/QxWrite1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindowbrick.cpp \
		insertbrick.cpp \
		menumanagerbrick.cpp \
		boldbrick.cpp \
		newfilebrick.cpp \
		toolbarbrick.cpp \
		italicbrick.cpp \
		openfilebrick.cpp \
		iconbrick.cpp \
		dialogbrick.cpp \
		fontbrick.cpp \
		colorbrick.cpp \
		savefunctionbrick.cpp \
		savehandlerbrick.cpp \
		saveguibrick.cpp \
		savemanagerbrick.cpp qrc_icons.cpp \
		moc_mainwindowbrick.cpp \
		moc_insertbrick.cpp \
		moc_menumanagerbrick.cpp \
		moc_boldbrick.cpp \
		moc_newfilebrick.cpp \
		moc_toolbarbrick.cpp \
		moc_italicbrick.cpp \
		moc_openfilebrick.cpp \
		moc_iconbrick.cpp \
		moc_dialogbrick.cpp \
		moc_fontbrick.cpp \
		moc_colorbrick.cpp \
		moc_savefunctionbrick.cpp \
		moc_savehandlerbrick.cpp \
		moc_saveguibrick.cpp \
		moc_savemanagerbrick.cpp
OBJECTS       = main.o \
		mainwindowbrick.o \
		insertbrick.o \
		menumanagerbrick.o \
		boldbrick.o \
		newfilebrick.o \
		toolbarbrick.o \
		italicbrick.o \
		openfilebrick.o \
		iconbrick.o \
		dialogbrick.o \
		fontbrick.o \
		colorbrick.o \
		savefunctionbrick.o \
		savehandlerbrick.o \
		saveguibrick.o \
		savemanagerbrick.o \
		qrc_icons.o \
		moc_mainwindowbrick.o \
		moc_insertbrick.o \
		moc_menumanagerbrick.o \
		moc_boldbrick.o \
		moc_newfilebrick.o \
		moc_toolbarbrick.o \
		moc_italicbrick.o \
		moc_openfilebrick.o \
		moc_iconbrick.o \
		moc_dialogbrick.o \
		moc_fontbrick.o \
		moc_colorbrick.o \
		moc_savefunctionbrick.o \
		moc_savehandlerbrick.o \
		moc_saveguibrick.o \
		moc_savemanagerbrick.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		qxwrite.pro mainwindowbrick.h \
		insertbrick.h \
		menumanagerbrick.h \
		boldbrick.h \
		newfilebrick.h \
		toolbarbrick.h \
		italicbrick.h \
		openfilebrick.h \
		iconbrick.h \
		dialogbrick.h \
		fontbrick.h \
		colorbrick.h \
		savefunctionbrick.h \
		savehandlerbrick.h \
		saveguibrick.h \
		savemanagerbrick.h main.cpp \
		mainwindowbrick.cpp \
		insertbrick.cpp \
		menumanagerbrick.cpp \
		boldbrick.cpp \
		newfilebrick.cpp \
		toolbarbrick.cpp \
		italicbrick.cpp \
		openfilebrick.cpp \
		iconbrick.cpp \
		dialogbrick.cpp \
		fontbrick.cpp \
		colorbrick.cpp \
		savefunctionbrick.cpp \
		savehandlerbrick.cpp \
		saveguibrick.cpp \
		savemanagerbrick.cpp
QMAKE_TARGET  = QxWrite
DESTDIR       = 
TARGET        = QxWrite


first: all
####### Build rules

QxWrite:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qxwrite.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		qxwrite.pro \
		icons.qrc
	$(QMAKE) -o Makefile qxwrite.pro -spec linux-g++ CONFIG+=debug
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
qxwrite.pro:
icons.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile qxwrite.pro -spec linux-g++ CONFIG+=debug

qmake_all: FORCE


all: Makefile QxWrite

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents icons.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindowbrick.h insertbrick.h menumanagerbrick.h boldbrick.h newfilebrick.h toolbarbrick.h italicbrick.h openfilebrick.h iconbrick.h dialogbrick.h fontbrick.h colorbrick.h savefunctionbrick.h savehandlerbrick.h saveguibrick.h savemanagerbrick.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindowbrick.cpp insertbrick.cpp menumanagerbrick.cpp boldbrick.cpp newfilebrick.cpp toolbarbrick.cpp italicbrick.cpp openfilebrick.cpp iconbrick.cpp dialogbrick.cpp fontbrick.cpp colorbrick.cpp savefunctionbrick.cpp savehandlerbrick.cpp saveguibrick.cpp savemanagerbrick.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp
qrc_icons.cpp: icons.qrc \
		/usr/lib/qt5/bin/rcc \
		icons/link.svg \
		icons/phone-missed.svg \
		icons/minimize-2.svg \
		icons/help-circle.svg \
		icons/bluetooth.svg \
		icons/align-center.svg \
		icons/stop-circle.svg \
		icons/cloud-lightning.svg \
		icons/cloud-drizzle.svg \
		icons/youtube.svg \
		icons/framer.svg \
		icons/zoom-out.svg \
		icons/heart.svg \
		icons/compass.svg \
		icons/file-minus.svg \
		icons/tool.svg \
		icons/percent.svg \
		icons/tag.svg \
		icons/smile.svg \
		icons/user-x.svg \
		icons/chevron-left.svg \
		icons/bell.svg \
		icons/trending-up.svg \
		icons/tablet.svg \
		icons/shuffle.svg \
		icons/more-vertical.svg \
		icons/paperclip.svg \
		icons/cast.svg \
		icons/cloud-snow.svg \
		icons/corner-right-up.svg \
		icons/life-buoy.svg \
		icons/dribbble.svg \
		icons/layers.svg \
		icons/pie-chart.svg \
		icons/key.svg \
		icons/moon.svg \
		icons/user-minus.svg \
		icons/skip-forward.svg \
		icons/edit-2.svg \
		icons/check-circle.svg \
		icons/log-in.svg \
		icons/navigation.svg \
		icons/package.svg \
		icons/thermometer.svg \
		icons/droplet.svg \
		icons/shopping-cart.svg \
		icons/arrow-down-circle.svg \
		icons/minus.svg \
		icons/aperture.svg \
		icons/coffee.svg \
		icons/calendar.svg \
		icons/phone-call.svg \
		icons/divide.svg \
		icons/navigation-2.svg \
		icons/zoom-in.svg \
		icons/trello.svg \
		icons/sidebar.svg \
		icons/mouse-pointer.svg \
		icons/user-check.svg \
		icons/book-open.svg \
		icons/git-branch.svg \
		icons/check.svg \
		icons/share-2.svg \
		icons/twitter.svg \
		icons/git-commit.svg \
		icons/users.svg \
		icons/alert-octagon.svg \
		icons/folder.svg \
		icons/at-sign.svg \
		icons/rss.svg \
		icons/arrow-right.svg \
		icons/feather.svg \
		icons/facebook.svg \
		icons/plus-circle.svg \
		icons/command.svg \
		icons/thumbs-up.svg \
		icons/arrow-down-right.svg \
		icons/battery-charging.svg \
		icons/trash-2.svg \
		icons/smartphone.svg \
		icons/image.svg \
		icons/minimize.svg \
		icons/corner-left-down.svg \
		icons/wifi.svg \
		icons/list.svg \
		icons/chevrons-left.svg \
		icons/zap-off.svg \
		icons/loader.svg \
		icons/lock.svg \
		icons/mic.svg \
		icons/umbrella.svg \
		icons/toggle-left.svg \
		icons/music.svg \
		icons/file-plus.svg \
		icons/anchor.svg \
		icons/arrow-right-circle.svg \
		icons/play-circle.svg \
		icons/arrow-down.svg \
		icons/search.svg \
		icons/eye-dropper.svg \
		icons/globe.svg \
		icons/corner-up-right.svg \
		icons/play.svg \
		icons/corner-down-right.svg \
		icons/unlock.svg \
		icons/tv.svg \
		icons/folder-minus.svg \
		icons/truck.svg \
		icons/align-right.svg \
		icons/target.svg \
		icons/send.svg \
		icons/skip-back.svg \
		icons/volume-1.svg \
		icons/folder-plus.svg \
		icons/wind.svg \
		icons/code.svg \
		icons/star.svg \
		icons/pause-circle.svg \
		icons/figma.svg \
		icons/user-plus.svg \
		icons/refresh-ccw.svg \
		icons/toggle-right.svg \
		icons/italic.svg \
		icons/triangle.svg \
		icons/fast-forward.svg \
		icons/chrome.svg \
		icons/eye.svg \
		icons/monitor.svg \
		icons/bell-off.svg \
		icons/home.svg \
		icons/sliders.svg \
		icons/x-circle.svg \
		icons/link-2.svg \
		icons/plus-square.svg \
		icons/rotate-cw.svg \
		icons/phone-outgoing.svg \
		icons/type.svg \
		icons/save.svg \
		icons/cloud-rain.svg \
		icons/arrow-down-left.svg \
		icons/voicemail.svg \
		icons/trash.svg \
		icons/move.svg \
		icons/crosshair.svg \
		icons/power.svg \
		icons/alert-circle.svg \
		icons/bold.svg \
		icons/twitch.svg \
		icons/plus.svg \
		icons/divide-circle.svg \
		icons/volume-x.svg \
		icons/arrow-left-circle.svg \
		icons/pen-tool.svg \
		icons/arrow-up.svg \
		icons/video.svg \
		icons/cpu.svg \
		icons/cloud.svg \
		icons/flag.svg \
		icons/watch.svg \
		icons/slack.svg \
		icons/hash.svg \
		icons/award.svg \
		icons/check-square.svg \
		icons/volume.svg \
		icons/grid.svg \
		icons/repeat.svg \
		icons/camera.svg \
		icons/more-horizontal.svg \
		icons/phone-incoming.svg \
		icons/codesandbox.svg \
		icons/arrow-up-circle.svg \
		icons/minus-circle.svg \
		icons/printer.svg \
		icons/share.svg \
		icons/gitlab.svg \
		icons/underline.svg \
		icons/corner-left-up.svg \
		icons/maximize.svg \
		icons/scissors.svg \
		icons/shopping-bag.svg \
		icons/color.svg \
		icons/arrow-up-left.svg \
		icons/mic-off.svg \
		icons/battery.svg \
		icons/pocket.svg \
		icons/x-square.svg \
		icons/shield-off.svg \
		icons/disc.svg \
		icons/camera-off.svg \
		icons/git-pull-request.svg \
		icons/bar-chart-2.svg \
		icons/table.svg \
		icons/maximize-2.svg \
		icons/film.svg \
		icons/chevron-down.svg \
		icons/chevron-right.svg \
		icons/gift.svg \
		icons/edit.svg \
		icons/bookmark.svg \
		icons/github.svg \
		icons/speaker.svg \
		icons/message-circle.svg \
		icons/refresh-cw.svg \
		icons/wifi-off.svg \
		icons/arrow-left.svg \
		icons/chevron-up.svg \
		icons/edit-3.svg \
		icons/clipboard.svg \
		icons/meh.svg \
		icons/corner-down-left.svg \
		icons/menu.svg \
		icons/chevrons-right.svg \
		icons/clock.svg \
		icons/instagram.svg \
		icons/activity.svg \
		icons/download.svg \
		icons/linkedin.svg \
		icons/inbox.svg \
		icons/align-left.svg \
		icons/terminal.svg \
		icons/filter.svg \
		icons/octagon.svg \
		icons/align-justify.svg \
		icons/log-out.svg \
		icons/circle.svg \
		icons/layout.svg \
		icons/hard-drive.svg \
		icons/minus-square.svg \
		icons/user.svg \
		icons/thumbs-down.svg \
		icons/open.svg \
		icons/hexagon.svg \
		icons/book.svg \
		icons/codepen.svg \
		icons/chevrons-up.svg \
		icons/x.svg \
		icons/x-octagon.svg \
		icons/dollar-sign.svg \
		icons/crop.svg \
		icons/upload.svg \
		icons/corner-up-left.svg \
		icons/phone-off.svg \
		icons/delete.svg \
		icons/briefcase.svg \
		icons/trending-down.svg \
		icons/sunset.svg \
		icons/mail.svg \
		icons/rewind.svg \
		icons/archive.svg \
		icons/download-cloud.svg \
		icons/phone.svg \
		icons/airplay.svg \
		icons/info.svg \
		icons/video-off.svg \
		icons/chevrons-down.svg \
		icons/shield.svg \
		icons/copy.svg \
		icons/phone-forwarded.svg \
		icons/credit-card.svg \
		icons/rotate-ccw.svg \
		icons/cloud-off.svg \
		icons/message-square.svg \
		icons/sunrise.svg \
		icons/external-link.svg \
		icons/server.svg \
		icons/font.svg \
		icons/upload-cloud.svg \
		icons/map.svg \
		icons/divide-square.svg \
		icons/slash.svg \
		icons/frown.svg \
		icons/bar-chart.svg \
		icons/alert-triangle.svg \
		icons/file.svg \
		icons/map-pin.svg \
		icons/settings.svg \
		icons/arrow-up-right.svg \
		icons/headphones.svg \
		icons/zap.svg \
		icons/file-text.svg \
		icons/database.svg \
		icons/pause.svg \
		icons/box.svg \
		icons/columns.svg \
		icons/eye-off.svg \
		icons/git-merge.svg \
		icons/square.svg \
		icons/corner-right-down.svg \
		icons/volume-2.svg \
		icons/sun.svg \
		icons/radio.svg
	/usr/lib/qt5/bin/rcc -name icons icons.qrc -o qrc_icons.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindowbrick.cpp moc_insertbrick.cpp moc_menumanagerbrick.cpp moc_boldbrick.cpp moc_newfilebrick.cpp moc_toolbarbrick.cpp moc_italicbrick.cpp moc_openfilebrick.cpp moc_iconbrick.cpp moc_dialogbrick.cpp moc_fontbrick.cpp moc_colorbrick.cpp moc_savefunctionbrick.cpp moc_savehandlerbrick.cpp moc_saveguibrick.cpp moc_savemanagerbrick.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindowbrick.cpp moc_insertbrick.cpp moc_menumanagerbrick.cpp moc_boldbrick.cpp moc_newfilebrick.cpp moc_toolbarbrick.cpp moc_italicbrick.cpp moc_openfilebrick.cpp moc_iconbrick.cpp moc_dialogbrick.cpp moc_fontbrick.cpp moc_colorbrick.cpp moc_savefunctionbrick.cpp moc_savehandlerbrick.cpp moc_saveguibrick.cpp moc_savemanagerbrick.cpp
moc_mainwindowbrick.cpp: mainwindowbrick.h \
		toolbarbrick.h \
		insertbrick.h \
		savemanagerbrick.h \
		saveguibrick.h \
		savehandlerbrick.h \
		savefunctionbrick.h \
		boldbrick.h \
		newfilebrick.h \
		italicbrick.h \
		openfilebrick.h \
		iconbrick.h \
		fontbrick.h \
		colorbrick.h \
		menumanagerbrick.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Downloads/editor/QxWriteProject/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Downloads/editor/QxWriteProject -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindowbrick.h -o moc_mainwindowbrick.cpp

moc_insertbrick.cpp: insertbrick.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Downloads/editor/QxWriteProject/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Downloads/editor/QxWriteProject -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include insertbrick.h -o moc_insertbrick.cpp

moc_menumanagerbrick.cpp: menumanagerbrick.h \
		insertbrick.h \
		savemanagerbrick.h \
		saveguibrick.h \
		savehandlerbrick.h \
		savefunctionbrick.h \
		boldbrick.h \
		newfilebrick.h \
		italicbrick.h \
		openfilebrick.h \
		fontbrick.h \
		colorbrick.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Downloads/editor/QxWriteProject/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Downloads/editor/QxWriteProject -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include menumanagerbrick.h -o moc_menumanagerbrick.cpp

moc_boldbrick.cpp: boldbrick.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Downloads/editor/QxWriteProject/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Downloads/editor/QxWriteProject -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include boldbrick.h -o moc_boldbrick.cpp

moc_newfilebrick.cpp: newfilebrick.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Downloads/editor/QxWriteProject/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Downloads/editor/QxWriteProject -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include newfilebrick.h -o moc_newfilebrick.cpp

moc_toolbarbrick.cpp: toolbarbrick.h \
		insertbrick.h \
		savemanagerbrick.h \
		saveguibrick.h \
		savehandlerbrick.h \
		savefunctionbrick.h \
		boldbrick.h \
		newfilebrick.h \
		italicbrick.h \
		openfilebrick.h \
		iconbrick.h \
		fontbrick.h \
		colorbrick.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Downloads/editor/QxWriteProject/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Downloads/editor/QxWriteProject -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include toolbarbrick.h -o moc_toolbarbrick.cpp

moc_italicbrick.cpp: italicbrick.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Downloads/editor/QxWriteProject/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Downloads/editor/QxWriteProject -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include italicbrick.h -o moc_italicbrick.cpp

moc_openfilebrick.cpp: openfilebrick.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Downloads/editor/QxWriteProject/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Downloads/editor/QxWriteProject -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include openfilebrick.h -o moc_openfilebrick.cpp

moc_iconbrick.cpp: iconbrick.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Downloads/editor/QxWriteProject/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Downloads/editor/QxWriteProject -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include iconbrick.h -o moc_iconbrick.cpp

moc_dialogbrick.cpp: dialogbrick.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Downloads/editor/QxWriteProject/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Downloads/editor/QxWriteProject -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include dialogbrick.h -o moc_dialogbrick.cpp

moc_fontbrick.cpp: fontbrick.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Downloads/editor/QxWriteProject/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Downloads/editor/QxWriteProject -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include fontbrick.h -o moc_fontbrick.cpp

moc_colorbrick.cpp: colorbrick.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Downloads/editor/QxWriteProject/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Downloads/editor/QxWriteProject -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include colorbrick.h -o moc_colorbrick.cpp

moc_savefunctionbrick.cpp: savefunctionbrick.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Downloads/editor/QxWriteProject/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Downloads/editor/QxWriteProject -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include savefunctionbrick.h -o moc_savefunctionbrick.cpp

moc_savehandlerbrick.cpp: savehandlerbrick.h \
		savefunctionbrick.h \
		saveguibrick.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Downloads/editor/QxWriteProject/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Downloads/editor/QxWriteProject -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include savehandlerbrick.h -o moc_savehandlerbrick.cpp

moc_saveguibrick.cpp: saveguibrick.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Downloads/editor/QxWriteProject/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Downloads/editor/QxWriteProject -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include saveguibrick.h -o moc_saveguibrick.cpp

moc_savemanagerbrick.cpp: savemanagerbrick.h \
		saveguibrick.h \
		savehandlerbrick.h \
		savefunctionbrick.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ares/Downloads/editor/QxWriteProject/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ares/Downloads/editor/QxWriteProject -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include savemanagerbrick.h -o moc_savemanagerbrick.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp mainwindowbrick.h \
		toolbarbrick.h \
		insertbrick.h \
		savemanagerbrick.h \
		saveguibrick.h \
		savehandlerbrick.h \
		savefunctionbrick.h \
		boldbrick.h \
		newfilebrick.h \
		italicbrick.h \
		openfilebrick.h \
		iconbrick.h \
		fontbrick.h \
		colorbrick.h \
		menumanagerbrick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindowbrick.o: mainwindowbrick.cpp mainwindowbrick.h \
		toolbarbrick.h \
		insertbrick.h \
		savemanagerbrick.h \
		saveguibrick.h \
		savehandlerbrick.h \
		savefunctionbrick.h \
		boldbrick.h \
		newfilebrick.h \
		italicbrick.h \
		openfilebrick.h \
		iconbrick.h \
		fontbrick.h \
		colorbrick.h \
		menumanagerbrick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindowbrick.o mainwindowbrick.cpp

insertbrick.o: insertbrick.cpp insertbrick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o insertbrick.o insertbrick.cpp

menumanagerbrick.o: menumanagerbrick.cpp menumanagerbrick.h \
		insertbrick.h \
		savemanagerbrick.h \
		saveguibrick.h \
		savehandlerbrick.h \
		savefunctionbrick.h \
		boldbrick.h \
		newfilebrick.h \
		italicbrick.h \
		openfilebrick.h \
		fontbrick.h \
		colorbrick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o menumanagerbrick.o menumanagerbrick.cpp

boldbrick.o: boldbrick.cpp boldbrick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o boldbrick.o boldbrick.cpp

newfilebrick.o: newfilebrick.cpp newfilebrick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newfilebrick.o newfilebrick.cpp

toolbarbrick.o: toolbarbrick.cpp toolbarbrick.h \
		insertbrick.h \
		savemanagerbrick.h \
		saveguibrick.h \
		savehandlerbrick.h \
		savefunctionbrick.h \
		boldbrick.h \
		newfilebrick.h \
		italicbrick.h \
		openfilebrick.h \
		iconbrick.h \
		fontbrick.h \
		colorbrick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o toolbarbrick.o toolbarbrick.cpp

italicbrick.o: italicbrick.cpp italicbrick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o italicbrick.o italicbrick.cpp

openfilebrick.o: openfilebrick.cpp openfilebrick.h \
		dialogbrick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o openfilebrick.o openfilebrick.cpp

iconbrick.o: iconbrick.cpp iconbrick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iconbrick.o iconbrick.cpp

dialogbrick.o: dialogbrick.cpp dialogbrick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogbrick.o dialogbrick.cpp

fontbrick.o: fontbrick.cpp fontbrick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fontbrick.o fontbrick.cpp

colorbrick.o: colorbrick.cpp colorbrick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o colorbrick.o colorbrick.cpp

savefunctionbrick.o: savefunctionbrick.cpp savefunctionbrick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o savefunctionbrick.o savefunctionbrick.cpp

savehandlerbrick.o: savehandlerbrick.cpp savehandlerbrick.h \
		savefunctionbrick.h \
		saveguibrick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o savehandlerbrick.o savehandlerbrick.cpp

saveguibrick.o: saveguibrick.cpp saveguibrick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o saveguibrick.o saveguibrick.cpp

savemanagerbrick.o: savemanagerbrick.cpp savemanagerbrick.h \
		saveguibrick.h \
		savehandlerbrick.h \
		savefunctionbrick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o savemanagerbrick.o savemanagerbrick.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

moc_mainwindowbrick.o: moc_mainwindowbrick.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindowbrick.o moc_mainwindowbrick.cpp

moc_insertbrick.o: moc_insertbrick.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_insertbrick.o moc_insertbrick.cpp

moc_menumanagerbrick.o: moc_menumanagerbrick.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_menumanagerbrick.o moc_menumanagerbrick.cpp

moc_boldbrick.o: moc_boldbrick.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_boldbrick.o moc_boldbrick.cpp

moc_newfilebrick.o: moc_newfilebrick.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newfilebrick.o moc_newfilebrick.cpp

moc_toolbarbrick.o: moc_toolbarbrick.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_toolbarbrick.o moc_toolbarbrick.cpp

moc_italicbrick.o: moc_italicbrick.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_italicbrick.o moc_italicbrick.cpp

moc_openfilebrick.o: moc_openfilebrick.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_openfilebrick.o moc_openfilebrick.cpp

moc_iconbrick.o: moc_iconbrick.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_iconbrick.o moc_iconbrick.cpp

moc_dialogbrick.o: moc_dialogbrick.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialogbrick.o moc_dialogbrick.cpp

moc_fontbrick.o: moc_fontbrick.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fontbrick.o moc_fontbrick.cpp

moc_colorbrick.o: moc_colorbrick.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_colorbrick.o moc_colorbrick.cpp

moc_savefunctionbrick.o: moc_savefunctionbrick.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_savefunctionbrick.o moc_savefunctionbrick.cpp

moc_savehandlerbrick.o: moc_savehandlerbrick.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_savehandlerbrick.o moc_savehandlerbrick.cpp

moc_saveguibrick.o: moc_saveguibrick.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_saveguibrick.o moc_saveguibrick.cpp

moc_savemanagerbrick.o: moc_savemanagerbrick.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_savemanagerbrick.o moc_savemanagerbrick.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

